// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGXy5nURgKNtXAVg_qIoZs-gTETOzU_tA',
    appId: '1:710848761016:web:584355f07a1e355648784d',
    messagingSenderId: '710848761016',
    projectId: 'recipeapp-32fce',
    authDomain: 'recipeapp-32fce.firebaseapp.com',
    storageBucket: 'recipeapp-32fce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtkh80uX0RRy2wLBNpari2OQWAzbe1SsA',
    appId: '1:710848761016:android:23ded8cf43c803ee48784d',
    messagingSenderId: '710848761016',
    projectId: 'recipeapp-32fce',
    storageBucket: 'recipeapp-32fce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6DNaQj0btCxYjeK9FJzPbumsOAdQ5WMg',
    appId: '1:710848761016:ios:3019a1d5d1d7ecb148784d',
    messagingSenderId: '710848761016',
    projectId: 'recipeapp-32fce',
    storageBucket: 'recipeapp-32fce.appspot.com',
    iosClientId: '710848761016-8ome75ootnst85prn7r8chklklmtqc1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRecipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6DNaQj0btCxYjeK9FJzPbumsOAdQ5WMg',
    appId: '1:710848761016:ios:3019a1d5d1d7ecb148784d',
    messagingSenderId: '710848761016',
    projectId: 'recipeapp-32fce',
    storageBucket: 'recipeapp-32fce.appspot.com',
    iosClientId: '710848761016-8ome75ootnst85prn7r8chklklmtqc1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRecipeApp',
  );
}
